/**
 * Email utilities for sharing bookings and sending notifications
 */

import type { Booking } from '@/hooks/useBookings'

export interface EmailShareOptions {
  to?: string
  subject?: string
  body?: string
  includeLink?: boolean
}

/**
 * Share booking via email
 */
export function shareBookingViaEmail(booking: any, options: EmailShareOptions = {}): void {
  const {
    to = '',
    subject = `Booking Details: ${booking.service?.title || booking.title || 'Service'}`,
    includeLink = true
  } = options

  const bookingUrl = `${window.location.origin}/dashboard/bookings/${booking.id}`
  
  const body = generateEmailBody(booking, {
    includeLink,
    customMessage: options.body
  })

  // Create mailto link
  const mailtoLink = `mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  
  // Open email client
  window.location.href = mailtoLink
}

/**
 * Generate formatted email body for booking
 */
function generateEmailBody(booking: any, options: { includeLink?: boolean; customMessage?: string } = {}): string {
  const { includeLink = true, customMessage = '' } = options
  
  const lines: string[] = []
  
  // Custom message if provided
  if (customMessage) {
    lines.push(customMessage)
    lines.push('')
    lines.push('---')
    lines.push('')
  }
  
  // Booking details
  lines.push('BOOKING DETAILS')
  lines.push('=' .repeat(50))
  lines.push('')
  lines.push(`Service: ${booking.service?.title || booking.title || 'N/A'}`)
  lines.push(`Status: ${booking.status || 'N/A'}`)
  lines.push(`Client: ${booking.client?.full_name || 'N/A'}`)
  lines.push(`Provider: ${booking.provider?.full_name || 'N/A'}`)
  lines.push(`Amount: ${booking.amount || 0} ${booking.currency || 'OMR'}`)
  lines.push(`Progress: ${booking.progress_percentage || 0}%`)
  lines.push(`Created: ${formatDateForEmail(booking.created_at)}`)
  
  if (booking.scheduled_date) {
    lines.push(`Scheduled: ${formatDateForEmail(booking.scheduled_date)}`)
  }
  
  if (booking.notes) {
    lines.push('')
    lines.push('Notes:')
    lines.push(booking.notes)
  }
  
  // Link to booking
  if (includeLink) {
    lines.push('')
    lines.push('---')
    lines.push('')
    lines.push(`View full details: ${window.location.origin}/dashboard/bookings/${booking.id}`)
  }
  
  // Footer
  lines.push('')
  lines.push('---')
  lines.push('This email was generated by the Marketing Dashboard')
  lines.push(`© ${new Date().getFullYear()} Digital Morph`)
  
  return lines.join('\n')
}

/**
 * Share multiple bookings via email
 */
export function shareMultipleBookingsViaEmail(bookings: Booking[], options: EmailShareOptions = {}): void {
  const {
    to = '',
    subject = `Bookings Report - ${bookings.length} Booking(s)`,
  } = options

  const body = generateMultipleBookingsEmailBody(bookings)

  const mailtoLink = `mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  window.location.href = mailtoLink
}

/**
 * Generate email body for multiple bookings
 */
function generateMultipleBookingsEmailBody(bookings: Booking[]): string {
  const lines: string[] = []
  
  lines.push('BOOKINGS REPORT')
  lines.push('=' .repeat(50))
  lines.push('')
  lines.push(`Total Bookings: ${bookings.length}`)
  lines.push(`Generated: ${new Date().toLocaleString()}`)
  lines.push('')
  lines.push('---')
  lines.push('')
  
  bookings.forEach((booking, index) => {
    lines.push(`${index + 1}. ${booking.service_title || 'Service'}`)
    lines.push(`   Status: ${booking.status}`)
    lines.push(`   Client: ${booking.client_name || 'N/A'}`)
    lines.push(`   Amount: ${booking.total_amount ? booking.total_amount.toFixed(2) : '0.00'} ${booking.currency || 'OMR'}`)
    lines.push(`   Progress: ${booking.progress_percentage || 0}%`)
    lines.push('')
  })
  
  lines.push('---')
  lines.push('')
  lines.push(`View all bookings: ${window.location.origin}/dashboard/bookings`)
  lines.push('')
  lines.push('This email was generated by the Marketing Dashboard')
  lines.push(`© ${new Date().getFullYear()} Digital Morph`)
  
  return lines.join('\n')
}

/**
 * Format date for email display
 */
function formatDateForEmail(dateStr?: string): string {
  if (!dateStr) return 'N/A'
  try {
    return new Date(dateStr).toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch {
    return 'Invalid Date'
  }
}

/**
 * Send notification email (would integrate with backend email service)
 */
export async function sendNotificationEmail(
  recipientEmail: string,
  subject: string,
  message: string,
  bookingId?: string
): Promise<{ success: boolean; error?: string }> {
  try {
    // In a real implementation, this would call a backend API
    // For now, we'll open the email client with pre-filled content
    const body = bookingId 
      ? `${message}\n\nBooking: ${window.location.origin}/dashboard/bookings/${bookingId}`
      : message
    
    const mailtoLink = `mailto:${recipientEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
    window.location.href = mailtoLink
    
    return { success: true }
  } catch (error) {
    console.error('Email notification error:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to send notification'
    }
  }
}

/**
 * Generate HTML email template
 */
export function generateHTMLEmailTemplate(booking: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 8px;
      text-align: center;
      margin-bottom: 30px;
    }
    .section {
      background: #f9fafb;
      padding: 20px;
      border-radius: 8px;
      margin: 15px 0;
    }
    .field {
      display: flex;
      margin: 10px 0;
      padding: 8px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .field:last-child {
      border-bottom: none;
    }
    .field-label {
      font-weight: 600;
      min-width: 120px;
      color: #6b7280;
    }
    .field-value {
      color: #1f2937;
    }
    .button {
      display: inline-block;
      background: #3b82f6;
      color: white;
      padding: 12px 24px;
      text-decoration: none;
      border-radius: 6px;
      margin: 20px 0;
      text-align: center;
    }
    .footer {
      text-align: center;
      color: #6b7280;
      font-size: 14px;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📋 Booking Details</h1>
    <p>${booking.service?.title || booking.title || 'Service Booking'}</p>
  </div>
  
  <div class="section">
    <h3 style="margin-top: 0; color: #3b82f6;">Service Information</h3>
    <div class="field">
      <div class="field-label">Service:</div>
      <div class="field-value">${booking.service?.title || booking.title || 'N/A'}</div>
    </div>
    <div class="field">
      <div class="field-label">Status:</div>
      <div class="field-value">${booking.status || 'N/A'}</div>
    </div>
  </div>
  
  <div class="section">
    <h3 style="margin-top: 0; color: #3b82f6;">Participants</h3>
    <div class="field">
      <div class="field-label">Client:</div>
      <div class="field-value">${booking.client?.full_name || 'N/A'}</div>
    </div>
    <div class="field">
      <div class="field-label">Provider:</div>
      <div class="field-value">${booking.provider?.full_name || 'N/A'}</div>
    </div>
  </div>
  
  <div class="section">
    <h3 style="margin-top: 0; color: #3b82f6;">Financial Details</h3>
    <div class="field">
      <div class="field-label">Amount:</div>
      <div class="field-value">${booking.amount || 0} ${booking.currency || 'OMR'}</div>
    </div>
    <div class="field">
      <div class="field-label">Progress:</div>
      <div class="field-value">${booking.progress_percentage || 0}%</div>
    </div>
  </div>
  
  <div style="text-align: center;">
    <a href="${window.location.origin}/dashboard/bookings/${booking.id}" class="button">
      View Full Details
    </a>
  </div>
  
  <div class="footer">
    <p>This email was generated by the Marketing Dashboard</p>
    <p>© ${new Date().getFullYear()} Digital Morph - All rights reserved</p>
  </div>
</body>
</html>
  `
}


